---
- name: copy nginx configuration
  template: src=config dest=/etc/nginx/sites-available/{{ teamcity_nginx_site_config }}
  notify: restart nginx

- name: disable default nginx configuration
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: enable nginx configuration
  file: src=/etc/nginx/sites-available/{{ teamcity_nginx_site_config }} dest=/etc/nginx/sites-enabled/{{ teamcity_nginx_site_config }} state=link
  notify: restart nginx

- name: validate nginx configuration
  command: /usr/sbin/nginx -t
  changed_when: false
