---
- name: apt-get update
  apt: update_cache=yes

- name: install CA certificates
  apt: name=ca-certificates

- name: set timezone
  copy:
    content: "{{ timezone }}\n"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: update timezone

- name: install ntp
  apt: name=ntp state=present

- name: configure locales
  locale_gen: name=en_US.UTF-8 state=present

- name: install systemd
  apt: name=systemd state=present
  when: ansible_distribution_release == 'jessie'

- name: install systemd-sysv
  apt: name='systemd-sysv' state=present
  notify: reboot
  when: ansible_distribution_release == 'jessie'
