---
- name: create postgres user
  postgresql_user:
    name: '{{ teamcity_db_user }}'
    password: '{{ teamcity_db_password }}'
  become: true
  become_user: postgres

- name: create postgres database
  postgresql_db:
    name: '{{ teamcity_db_name }}'
    owner: '{{ teamcity_db_user }}'
  become: true
  become_user: postgres

- name: set synchronous_commit=off
  lineinfile:
    dest: '/etc/postgresql/{{ postgres_version }}/main/postgresql.conf'
    insertafter: '^#synchronous_commit'
    line: 'synchronous_commit = off'
  notify: restart postgres
